title: My Blog Name
title_seperator: '-' # default is '-'
locale: ko-KR # default is none
date_format: # '%Y. %m. %d' #default is "%B %-d, %Y"
permalink: /:title
siteinfo:
  name: NameNameNameNameNameNameNameNameNameNameNameNameNameNameNameNameNameNameNameName
  description: DescriptionDescriptionDescriptionDescriptionDescriptionDescriptionDescriptionDescriptionDescriptionDescriptionDescription
  avatar: /assets/images/avatar.png # TODO : baseurl에 더하기
  socials:
    # github: https://github.com/leetaewook

pagination:
  enabled: true
  per_page: 4
  permalink: '/page:num/'
  limit: 0
  sort_field: 'date'
  sort_reverse: true
  trail:
    before: 2
    after: 2

autopages:
  enabled: true
  collections:
    enabled: false
  categories:
    enabled: false
  tags:
    enabled: true
    layouts:
      - autopage_tags.html

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

defaults:
  - values:
      layout: post

plugins:
  - jekyll-paginate-v2
