# Site settings
title: My Blog Name
description: 'my something blog'
title_seperator: '-' # "-" (default), "|", ...
locale: null # null (default), en-US, zh-CN, ...
date_format: # "%B %-d, %Y" (default), "%Y. %m. %d", ... https://www.shortcutfoo.com/app/dojos/ruby-date-format-strftime/cheatsheet
og_image: # Default OpenGraph Image
footer_copyright: '&copy; 2022 Example Site'

# Profile
profile:
  name: NameNameNameNameNameNameNameNameNameNameNameNameNameNameNameNameNameNameNameName
  description: DescriptionDescriptionDescriptionDescriptionDescriptionDescriptionDescriptionDescriptionDescriptionDescriptionDescription
  avatar: /assets/images/avatar.png # TODO : baseurl에 더하기
  socials:
    github:
    twitter:
    facebook:
    instagram:
    youtube:

# Comments
comments:
  provider: false # false (default), "utterances", "disqus"
  utterances:
    repo: # "github_username/repo_name"
    theme: # "github-light" (default), "github-dark", "preferred-color-scheme", "github-dark-orange", "icy-dark", "dark-blue", "photon-dark", "boxy-light", "gruvbox-dark"
    issue_term: # "pathname" (default)
    label: # null (default), Yout github repo issue label
  disqus:
    shortname:

# SEO Related
google_site_verification:
bing_site_verification:
naver_site_verification:
yandex_site_verification:
baidu_site_verification:

# Analytics
analytics:
  provider: false # false (default), "google", "google-universal", "google-gtag"
  google:
    tracking_id:
    anonymize_ip: # true, false (default)

# Your post default values
defaults:
  - values:
      layout: post
      comments: true

permalink: /:title # "/:title", ":year:month:day/:title", ... https://jekyllrb.com/docs/permalinks/
baseurl: # TODO

pagination:
  enabled: true
  per_page: 4
  permalink: '/page:num/'
  limit: 0
  sort_field: 'date'
  sort_reverse: true
  trail:
    before: 2
    after: 2

autopages:
  enabled: true
  collections:
    enabled: false
  categories:
    enabled: false
  tags:
    enabled: true
    layouts:
      - autopage_tags.html

markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

plugins:
  - jekyll-paginate-v2
  - jekyll-sitemap
  - jekyll-gist
