title: My Blog Name
title_seperator: '-' # default is '-'
locale: ko-KR # default is none
date_format: '%Y. %m. %d' #default is "%B %-d, %Y"

siteinfo:
  name: NameNameNameNameNameNameNameNameNameNameNameNameNameNameNameNameNameNameNameName
  description: DescriptionDescriptionDescriptionDescriptionDescriptionDescriptionDescriptionDescriptionDescriptionDescriptionDescription
  avatar: /assets/images/avatar.png # TODO : baseurl에 더하기
  socials:
    # github: https://github.com/leetaewook

permalink: /:title

pagination:
  enabled: true
  per_page: 4
  permalink: '/page:num/'
  limit: 0
  sort_field: 'date'
  sort_reverse:
  trail:
    before: 2
    after: 2

autopages:
  enabled: true
  collections:
    enabled: false
  tags:
    enabled: true
    layouts:
      - autopage_tags.html

defaults:
  - values:
      layout: post

plugins:
  - jekyll-paginate-v2
